/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:52:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import com.tap.model.Cart;
import com.tap.model.Cartitem;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.tap.model.Cart");
    _jspx_imports_classes.add("com.tap.model.Cartitem");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                ");
 /* Authentication Check */ Object userObj=session.getAttribute("user"); if (userObj==null) {
                    response.sendRedirect("login.jsp"); return; } Cart cart=(Cart) session.getAttribute("cart"); 
      out.write("\r\n");
      out.write("                    <!DOCTYPE html>\r\n");
      out.write("                    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                    <head>\r\n");
      out.write("                        <meta charset=\"UTF-8\">\r\n");
      out.write("                        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                        <title>My Cart - FoodExpress</title>\r\n");
      out.write("                        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("                            rel=\"stylesheet\">\r\n");
      out.write("                        <link rel=\"stylesheet\"\r\n");
      out.write("                            href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" />\r\n");
      out.write("                        <style>\r\n");
      out.write("                            body {\r\n");
      out.write("                                background: #f5f7fa;\r\n");
      out.write("                                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .navbar-custom {\r\n");
      out.write("                                background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .navbar-custom .navbar-brand {\r\n");
      out.write("                                font-weight: bold;\r\n");
      out.write("                                font-size: 24px;\r\n");
      out.write("                                color: white !important;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .navbar-custom .nav-link {\r\n");
      out.write("                                color: white !important;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .cart-container {\r\n");
      out.write("                                max-width: 900px;\r\n");
      out.write("                                margin: 40px auto;\r\n");
      out.write("                                padding: 0 20px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .card {\r\n");
      out.write("                                border: none;\r\n");
      out.write("                                border-radius: 15px;\r\n");
      out.write("                                box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .card-header {\r\n");
      out.write("                                background: white;\r\n");
      out.write("                                border-bottom: 2px solid #f0f0f0;\r\n");
      out.write("                                padding: 20px;\r\n");
      out.write("                                font-weight: 700;\r\n");
      out.write("                                font-size: 20px;\r\n");
      out.write("                                border-radius: 15px 15px 0 0 !important;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .cart-item {\r\n");
      out.write("                                display: grid;\r\n");
      out.write("                                grid-template-columns: 1fr auto auto;\r\n");
      out.write("                                align-items: center;\r\n");
      out.write("                                gap: 20px;\r\n");
      out.write("                                padding: 20px;\r\n");
      out.write("                                border-bottom: 1px solid #eee;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .cart-item:last-child {\r\n");
      out.write("                                border-bottom: none;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .item-info h5 {\r\n");
      out.write("                                margin: 0;\r\n");
      out.write("                                font-weight: 700;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .item-info p {\r\n");
      out.write("                                margin: 0;\r\n");
      out.write("                                color: #888;\r\n");
      out.write("                                font-size: 14px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .qty-controls {\r\n");
      out.write("                                display: flex;\r\n");
      out.write("                                align-items: center;\r\n");
      out.write("                                gap: 10px;\r\n");
      out.write("                                background: #f8f9fa;\r\n");
      out.write("                                border-radius: 30px;\r\n");
      out.write("                                padding: 5px 15px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-qty {\r\n");
      out.write("                                border: none;\r\n");
      out.write("                                background: none;\r\n");
      out.write("                                font-size: 18px;\r\n");
      out.write("                                font-weight: 700;\r\n");
      out.write("                                color: #FF6B00;\r\n");
      out.write("                                cursor: pointer;\r\n");
      out.write("                                padding: 0 5px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .qty-display {\r\n");
      out.write("                                font-weight: 700;\r\n");
      out.write("                                width: 25px;\r\n");
      out.write("                                text-align: center;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .item-price {\r\n");
      out.write("                                font-weight: 800;\r\n");
      out.write("                                font-size: 18px;\r\n");
      out.write("                                color: #333;\r\n");
      out.write("                                width: 100px;\r\n");
      out.write("                                text-align: right;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .cart-footer {\r\n");
      out.write("                                padding: 30px;\r\n");
      out.write("                                background: #fafafa;\r\n");
      out.write("                                border-radius: 0 0 15px 15px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .total-section {\r\n");
      out.write("                                display: flex;\r\n");
      out.write("                                justify-content: flex-end;\r\n");
      out.write("                                align-items: center;\r\n");
      out.write("                                gap: 40px;\r\n");
      out.write("                                margin-bottom: 20px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .total-label {\r\n");
      out.write("                                font-size: 18px;\r\n");
      out.write("                                color: #666;\r\n");
      out.write("                                font-weight: 600;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .total-amount {\r\n");
      out.write("                                font-size: 28px;\r\n");
      out.write("                                font-weight: 800;\r\n");
      out.write("                                color: #FF6B00;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-checkout {\r\n");
      out.write("                                background: #FF6B00;\r\n");
      out.write("                                color: white;\r\n");
      out.write("                                border: none;\r\n");
      out.write("                                padding: 15px 40px;\r\n");
      out.write("                                border-radius: 12px;\r\n");
      out.write("                                font-weight: 700;\r\n");
      out.write("                                font-size: 18px;\r\n");
      out.write("                                transition: 0.3s;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-checkout:hover {\r\n");
      out.write("                                background: #E65A00;\r\n");
      out.write("                                transform: translateY(-3px);\r\n");
      out.write("                                box-shadow: 0 5px 15px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .btn-checkout:disabled {\r\n");
      out.write("                                background: #ccc;\r\n");
      out.write("                                cursor: not-allowed;\r\n");
      out.write("                                transform: none;\r\n");
      out.write("                                box-shadow: none;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .empty-cart {\r\n");
      out.write("                                text-align: center;\r\n");
      out.write("                                padding: 60px 20px;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            .empty-cart i {\r\n");
      out.write("                                font-size: 80px;\r\n");
      out.write("                                color: #ddd;\r\n");
      out.write("                                margin-bottom: 20px;\r\n");
      out.write("                            }\r\n");
      out.write("                        </style>\r\n");
      out.write("                    </head>\r\n");
      out.write("\r\n");
      out.write("                    <body>\r\n");
      out.write("                        <nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom sticky-top\">\r\n");
      out.write("                            <div class=\"container\">\r\n");
      out.write("                                <a class=\"navbar-brand\" href=\"home.jsp\"><i\r\n");
      out.write("                                        class=\"fas fa-utensils me-2\"></i>FoodExpress</a>\r\n");
      out.write("                                <div class=\"ms-auto\">\r\n");
      out.write("                                    <a href=\"home.jsp\" class=\"nav-link d-inline-block me-3\"><i\r\n");
      out.write("                                            class=\"fas fa-home me-1\"></i>Home</a>\r\n");
      out.write("                                    <a href=\"orders\" class=\"nav-link d-inline-block me-3\"><i\r\n");
      out.write("                                            class=\"fas fa-shopping-bag me-1\"></i>My Orders</a>\r\n");
      out.write("                                    <a href=\"LogoutServlet\" class=\"nav-link d-inline-block\"><i\r\n");
      out.write("                                            class=\"fas fa-sign-out-alt me-1\"></i>Logout</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"cart-container\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart me-2 text-primary\"></i>My Shopping Cart\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body p-0\">\r\n");
      out.write("                                    ");
 if (cart !=null && cart.getItems() !=null && !cart.getItems().isEmpty()) { 
      out.write("\r\n");
      out.write("                                        <div class=\"cart-items\">\r\n");
      out.write("                                            ");
 for (Map.Entry<Integer, Cartitem> entry : cart.getItems().entrySet()) {
                                                Cartitem item = entry.getValue();
                                                
      out.write("\r\n");
      out.write("                                                <div class=\"cart-item\">\r\n");
      out.write("                                                    <div class=\"item-info\">\r\n");
      out.write("                                                        <h5>\r\n");
      out.write("                                                            ");
      out.print( item.getItemName() );
      out.write("\r\n");
      out.write("                                                        </h5>\r\n");
      out.write("                                                        <p>&#8377; ");
      out.print( item.getPrice() );
      out.write(" per unit</p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"qty-controls\">\r\n");
      out.write("                                                        <form action=\"CartServlet\" method=\"POST\" class=\"m-0\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"menuId\"\r\n");
      out.write("                                                                value=\"");
      out.print( item.getMenuId() );
      out.write("\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"quantity\"\r\n");
      out.write("                                                                value=\"");
      out.print( item.getQuantity() - 1 );
      out.write("\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"from\" value=\"cart\">\r\n");
      out.write("                                                            <button type=\"submit\" class=\"btn-qty\" ");
      out.print(item.getQuantity()
                                                                <=1 ? "disabled" : "" );
      out.write(">-</button>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                        <div class=\"qty-display\">\r\n");
      out.write("                                                            ");
      out.print( item.getQuantity() );
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <form action=\"CartServlet\" method=\"POST\" class=\"m-0\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"menuId\"\r\n");
      out.write("                                                                value=\"");
      out.print( item.getMenuId() );
      out.write("\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"quantity\"\r\n");
      out.write("                                                                value=\"");
      out.print( item.getQuantity() + 1 );
      out.write("\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"from\" value=\"cart\">\r\n");
      out.write("                                                            <button type=\"submit\" class=\"btn-qty\">+</button>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                        <form action=\"CartServlet\" method=\"POST\" class=\"ms-3 m-0\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"action\" value=\"remove\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"menuId\"\r\n");
      out.write("                                                                value=\"");
      out.print( item.getMenuId() );
      out.write("\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"from\" value=\"cart\">\r\n");
      out.write("                                                            <button type=\"submit\"\r\n");
      out.write("                                                                class=\"btn border-0 p-0 text-danger\"><i\r\n");
      out.write("                                                                    class=\"fas fa-trash\"></i></button>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"item-price\">\r\n");
      out.write("                                                        &#8377; ");
      out.print( String.format("%.2f", item.getPrice() *
                                                            item.getQuantity()) );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"cart-footer\">\r\n");
      out.write("                                            <div class=\"total-section\">\r\n");
      out.write("                                                <span class=\"total-label\">Subtotal</span>\r\n");
      out.write("                                                <span class=\"total-amount\">&#8377; ");
      out.print( String.format("%.2f",
                                                        cart.getTotalPrice()) );
      out.write("</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                <a href=\"menu.jsp\" class=\"btn btn-outline-secondary rounded-pill px-4\">\r\n");
      out.write("                                                    <i class=\"fas fa-arrow-left me-2\"></i>Add More Items\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <form action=\"CheckoutServlet\" method=\"POST\">\r\n");
      out.write("                                                    <button type=\"submit\" class=\"btn-checkout\">Proceed to\r\n");
      out.write("                                                        Checkout</button>\r\n");
      out.write("                                                </form>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        ");
 } else { 
      out.write("\r\n");
      out.write("                                            <div class=\"empty-cart\">\r\n");
      out.write("                                                <i class=\"fas fa-shopping-basket\"></i>\r\n");
      out.write("                                                <h3>Your cart is empty!</h3>\r\n");
      out.write("                                                <p class=\"text-muted\">Looks like you haven't added anything to your cart\r\n");
      out.write("                                                    yet.</p>\r\n");
      out.write("                                                <a href=\"home.jsp\"\r\n");
      out.write("                                                    class=\"btn btn-primary mt-4 px-5 py-3 rounded-pill fw-bold\">Explore\r\n");
      out.write("                                                    Restaurants</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </body>\r\n");
      out.write("\r\n");
      out.write("                    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
