/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:51:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.tap.model.Resturant;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.model.Resturant");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>FoodExpress - Order Delicious Food Online</title>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("                <style>\r\n");
      out.write("                    * {\r\n");
      out.write("                        margin: 0;\r\n");
      out.write("                        padding: 0;\r\n");
      out.write("                        box-sizing: border-box;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    body {\r\n");
      out.write("                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                        background: #0F0F0F;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        min-height: 100vh;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Navbar */\r\n");
      out.write("                    .navbar {\r\n");
      out.write("                        background: rgba(26, 26, 26, 0.95);\r\n");
      out.write("                        backdrop-filter: blur(10px);\r\n");
      out.write("                        padding: 20px 0;\r\n");
      out.write("                        position: sticky;\r\n");
      out.write("                        top: 0;\r\n");
      out.write("                        z-index: 1000;\r\n");
      out.write("                        border-bottom: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .navbar-container {\r\n");
      out.write("                        max-width: 1400px;\r\n");
      out.write("                        margin: 0 auto;\r\n");
      out.write("                        padding: 0 30px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 12px;\r\n");
      out.write("                        text-decoration: none;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-icon {\r\n");
      out.write("                        width: 45px;\r\n");
      out.write("                        height: 45px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                        box-shadow: 0 4px 15px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-icon i {\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        font-size: 22px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-text {\r\n");
      out.write("                        font-size: 26px;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        letter-spacing: -0.5px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-links {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        gap: 30px;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-link {\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                        text-decoration: none;\r\n");
      out.write("                        font-size: 15px;\r\n");
      out.write("                        font-weight: 500;\r\n");
      out.write("                        transition: color 0.3s;\r\n");
      out.write("                        padding: 8px 16px;\r\n");
      out.write("                        border-radius: 8px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-link:hover {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                        background: rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-logout {\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        padding: 10px 24px;\r\n");
      out.write("                        border-radius: 10px;\r\n");
      out.write("                        font-size: 14px;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                        box-shadow: 0 4px 15px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-logout:hover {\r\n");
      out.write("                        transform: translateY(-2px);\r\n");
      out.write("                        box-shadow: 0 6px 20px rgba(255, 107, 0, 0.4);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Hero Section */\r\n");
      out.write("                    .hero {\r\n");
      out.write("                        background: linear-gradient(135deg, rgba(255, 107, 0, 0.1) 0%, rgba(26, 26, 26, 0.5) 100%);\r\n");
      out.write("                        padding: 80px 30px;\r\n");
      out.write("                        text-align: center;\r\n");
      out.write("                        border-bottom: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .hero h1 {\r\n");
      out.write("                        font-size: 56px;\r\n");
      out.write("                        font-weight: 800;\r\n");
      out.write("                        margin-bottom: 20px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FFFFFF 0%, #FF6B00 100%);\r\n");
      out.write("                        -webkit-background-clip: text;\r\n");
      out.write("                        -webkit-text-fill-color: transparent;\r\n");
      out.write("                        background-clip: text;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .hero p {\r\n");
      out.write("                        font-size: 20px;\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                        margin-bottom: 40px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .search-bar {\r\n");
      out.write("                        max-width: 600px;\r\n");
      out.write("                        margin: 0 auto;\r\n");
      out.write("                        position: relative;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .search-bar input {\r\n");
      out.write("                        width: 100%;\r\n");
      out.write("                        padding: 18px 60px 18px 24px;\r\n");
      out.write("                        background: rgba(42, 42, 42, 0.8);\r\n");
      out.write("                        border: 2px solid rgba(255, 107, 0, 0.2);\r\n");
      out.write("                        border-radius: 50px;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        font-size: 16px;\r\n");
      out.write("                        outline: none;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .search-bar input:focus {\r\n");
      out.write("                        border-color: #FF6B00;\r\n");
      out.write("                        box-shadow: 0 0 0 4px rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .search-bar button {\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        right: 6px;\r\n");
      out.write("                        top: 50%;\r\n");
      out.write("                        transform: translateY(-50%);\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        width: 48px;\r\n");
      out.write("                        height: 48px;\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .search-bar button:hover {\r\n");
      out.write("                        transform: translateY(-50%) scale(1.05);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Main Content */\r\n");
      out.write("                    .container {\r\n");
      out.write("                        max-width: 1400px;\r\n");
      out.write("                        margin: 0 auto;\r\n");
      out.write("                        padding: 60px 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .section-header {\r\n");
      out.write("                        margin-bottom: 40px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .section-header h2 {\r\n");
      out.write("                        font-size: 36px;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        margin-bottom: 10px;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .section-header p {\r\n");
      out.write("                        font-size: 16px;\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Restaurant Grid */\r\n");
      out.write("                    .restaurant-grid {\r\n");
      out.write("                        display: grid;\r\n");
      out.write("                        grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));\r\n");
      out.write("                        gap: 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-card {\r\n");
      out.write("                        background: rgba(26, 26, 26, 0.8);\r\n");
      out.write("                        border-radius: 20px;\r\n");
      out.write("                        overflow: hidden;\r\n");
      out.write("                        transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n");
      out.write("                        border: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        position: relative;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-card:hover {\r\n");
      out.write("                        transform: translateY(-10px);\r\n");
      out.write("                        box-shadow: 0 20px 40px rgba(255, 107, 0, 0.2);\r\n");
      out.write("                        border-color: rgba(255, 107, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-image {\r\n");
      out.write("                        width: 100%;\r\n");
      out.write("                        height: 220px;\r\n");
      out.write("                        object-fit: cover;\r\n");
      out.write("                        transition: transform 0.4s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-card:hover .restaurant-image {\r\n");
      out.write("                        transform: scale(1.05);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-info {\r\n");
      out.write("                        padding: 24px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-name {\r\n");
      out.write("                        font-size: 22px;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        margin-bottom: 8px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-cuisine {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                        font-size: 14px;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        margin-bottom: 12px;\r\n");
      out.write("                        text-transform: uppercase;\r\n");
      out.write("                        letter-spacing: 0.5px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .restaurant-meta {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        gap: 20px;\r\n");
      out.write("                        margin-bottom: 16px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .meta-item {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 6px;\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                        font-size: 14px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .meta-item i {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .rating {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 6px;\r\n");
      out.write("                        color: #FFB84D;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-view-menu {\r\n");
      out.write("                        width: 100%;\r\n");
      out.write("                        padding: 14px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        font-size: 15px;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                        margin-top: 12px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-view-menu:hover {\r\n");
      out.write("                        transform: translateY(-2px);\r\n");
      out.write("                        box-shadow: 0 8px 20px rgba(255, 107, 0, 0.4);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .no-restaurants {\r\n");
      out.write("                        text-align: center;\r\n");
      out.write("                        padding: 80px 20px;\r\n");
      out.write("                        color: #666;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .no-restaurants i {\r\n");
      out.write("                        font-size: 64px;\r\n");
      out.write("                        margin-bottom: 20px;\r\n");
      out.write("                        color: #333;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Responsive */\r\n");
      out.write("                    @media (max-width: 768px) {\r\n");
      out.write("                        .hero h1 {\r\n");
      out.write("                            font-size: 36px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .restaurant-grid {\r\n");
      out.write("                            grid-template-columns: 1fr;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .nav-links {\r\n");
      out.write("                            gap: 15px;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .navbar-container {\r\n");
      out.write("                            flex-direction: column;\r\n");
      out.write("                            gap: 20px;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Chatbot Styles */\r\n");
      out.write("                    .chat-widget {\r\n");
      out.write("                        position: fixed;\r\n");
      out.write("                        bottom: 30px;\r\n");
      out.write("                        right: 30px;\r\n");
      out.write("                        z-index: 2000;\r\n");
      out.write("                        font-family: inherit;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-button {\r\n");
      out.write("                        width: 60px;\r\n");
      out.write("                        height: 60px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        font-size: 24px;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        box-shadow: 0 10px 25px rgba(255, 107, 0, 0.4);\r\n");
      out.write("                        transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-button:hover {\r\n");
      out.write("                        transform: scale(1.1) rotate(5deg);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-window {\r\n");
      out.write("                        position: absolute;\r\n");
      out.write("                        bottom: 80px;\r\n");
      out.write("                        right: 0;\r\n");
      out.write("                        width: 350px;\r\n");
      out.write("                        height: 500px;\r\n");
      out.write("                        background: rgba(26, 26, 26, 0.98);\r\n");
      out.write("                        backdrop-filter: blur(15px);\r\n");
      out.write("                        border-radius: 20px;\r\n");
      out.write("                        border: 1px solid rgba(255, 107, 0, 0.2);\r\n");
      out.write("                        display: none;\r\n");
      out.write("                        flex-direction: column;\r\n");
      out.write("                        overflow: hidden;\r\n");
      out.write("                        box-shadow: 0 15px 50px rgba(0, 0, 0, 0.5);\r\n");
      out.write("                        animation: slideIn 0.3s ease-out;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    @keyframes slideIn {\r\n");
      out.write("                        from {\r\n");
      out.write("                            opacity: 0;\r\n");
      out.write("                            transform: translateY(20px);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        to {\r\n");
      out.write("                            opacity: 1;\r\n");
      out.write("                            transform: translateY(0);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-header {\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                        padding: 20px;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-header h4 {\r\n");
      out.write("                        margin: 0;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-messages {\r\n");
      out.write("                        flex: 1;\r\n");
      out.write("                        padding: 20px;\r\n");
      out.write("                        overflow-y: auto;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        flex-direction: column;\r\n");
      out.write("                        gap: 15px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .message {\r\n");
      out.write("                        max-width: 80%;\r\n");
      out.write("                        padding: 12px 16px;\r\n");
      out.write("                        border-radius: 15px;\r\n");
      out.write("                        font-size: 14px;\r\n");
      out.write("                        line-height: 1.5;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .bot-message {\r\n");
      out.write("                        align-self: flex-start;\r\n");
      out.write("                        background: rgba(42, 42, 42, 0.8);\r\n");
      out.write("                        color: #EEE;\r\n");
      out.write("                        border-bottom-left-radius: 2px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .user-message {\r\n");
      out.write("                        align-self: flex-end;\r\n");
      out.write("                        background: #FF6B00;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        border-bottom-right-radius: 2px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-input-area {\r\n");
      out.write("                        padding: 15px;\r\n");
      out.write("                        background: rgba(42, 42, 42, 0.4);\r\n");
      out.write("                        border-top: 1px solid rgba(255, 255, 255, 0.05);\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        gap: 10px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-input-area input {\r\n");
      out.write("                        flex: 1;\r\n");
      out.write("                        background: rgba(20, 20, 20, 0.8);\r\n");
      out.write("                        border: 1px solid rgba(255, 107, 0, 0.2);\r\n");
      out.write("                        border-radius: 10px;\r\n");
      out.write("                        padding: 10px 15px;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        outline: none;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-input-area button {\r\n");
      out.write("                        background: #FF6B00;\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        width: 40px;\r\n");
      out.write("                        height: 40px;\r\n");
      out.write("                        border-radius: 10px;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .chat-input-area button:hover {\r\n");
      out.write("                        background: #FF8533;\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <!-- Navbar -->\r\n");
      out.write("                <nav class=\"navbar\">\r\n");
      out.write("                    <div class=\"navbar-container\">\r\n");
      out.write("                        <a href=\"home.jsp\" class=\"logo\">\r\n");
      out.write("                            <div class=\"logo-icon\">\r\n");
      out.write("                                <i class=\"fas fa-utensils\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"logo-text\">FoodExpress</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"nav-links\">\r\n");
      out.write("                            <a href=\"home.jsp\" class=\"nav-link\">Home</a>\r\n");
      out.write("                            <a href=\"orders\" class=\"nav-link\">My Orders</a>\r\n");
      out.write("                            <a href=\"cart.jsp\" class=\"nav-link\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart\"></i> Cart\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <form action=\"LogoutServlet\" method=\"POST\" style=\"margin: 0;\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-logout\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("\r\n");
      out.write("                <!-- Hero Section -->\r\n");
      out.write("                <section class=\"hero\">\r\n");
      out.write("                    <h1>Order Your Favorite Food</h1>\r\n");
      out.write("                    <p>Delicious meals delivered to your doorstep in minutes</p>\r\n");
      out.write("                    <div class=\"search-bar\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"Search for restaurants or cuisines...\" id=\"searchInput\">\r\n");
      out.write("                        <button><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- Main Content -->\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"section-header\">\r\n");
      out.write("                        <h2>Popular Restaurants</h2>\r\n");
      out.write("                        <p>Discover the best restaurants near you</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"restaurant-grid\">\r\n");
      out.write("                        ");
 List<Resturant> restaurants = (List<Resturant>) request.getAttribute("resturants");
                                if (restaurants != null && !restaurants.isEmpty()) {
                                for (Resturant restaurant : restaurants) {
                                
      out.write("\r\n");
      out.write("                                <div class=\"restaurant-card\"\r\n");
      out.write("                                    onclick=\"window.location.href='menu.jsp?restaurantId=");
      out.print( restaurant.getRestaurantId() );
      out.write("'\">\r\n");
      out.write("                                    ");
 String imageUrl=restaurant.getImageUrl(); if (imageUrl==null ||
                                        imageUrl.isEmpty()) { imageUrl="images/restaurant-default.jpg" ; } 
      out.write("\r\n");
      out.write("                                        <img src=\"");
      out.print( imageUrl );
      out.write("\" alt=\"");
      out.print( restaurant.getRestaurantName() );
      out.write("\"\r\n");
      out.write("                                            class=\"restaurant-image\">\r\n");
      out.write("                                        <div class=\"restaurant-info\">\r\n");
      out.write("                                            <h3 class=\"restaurant-name\">\r\n");
      out.write("                                                ");
      out.print( restaurant.getRestaurantName() );
      out.write("\r\n");
      out.write("                                            </h3>\r\n");
      out.write("                                            <div class=\"restaurant-cuisine\">\r\n");
      out.write("                                                ");
      out.print( restaurant.getCuisineType() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"restaurant-meta\">\r\n");
      out.write("                                                <div class=\"meta-item rating\">\r\n");
      out.write("                                                    <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                                    <span>\r\n");
      out.write("                                                        ");
      out.print( restaurant.getRating() );
      out.write("\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"meta-item\">\r\n");
      out.write("                                                    <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                                                    <span>\r\n");
      out.write("                                                        ");
      out.print( restaurant.getDeliveryTime() );
      out.write(" mins\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <button class=\"btn-view-menu\">\r\n");
      out.write("                                                <i class=\"fas fa-utensils\"></i> View Menu\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } } else { 
      out.write("\r\n");
      out.write("                                    <div class=\"no-restaurants\">\r\n");
      out.write("                                        <i class=\"fas fa-store-slash\"></i>\r\n");
      out.write("                                        <h3>No restaurants available</h3>\r\n");
      out.write("                                        <p>Please check back later</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Chatbot Widget -->\r\n");
      out.write("                <div class=\"chat-widget\">\r\n");
      out.write("                    <div class=\"chat-button\" onclick=\"toggleChat()\">\r\n");
      out.write("                        <i class=\"fas fa-comment-dots\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chat-window\" id=\"chatWindow\">\r\n");
      out.write("                        <div class=\"chat-header\">\r\n");
      out.write("                            <h4><i class=\"fas fa-robot\"></i> FoodExpress Support</h4>\r\n");
      out.write("                            <i class=\"fas fa-times\" style=\"cursor: pointer;\" onclick=\"toggleChat()\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-messages\" id=\"chatMessages\">\r\n");
      out.write("                            <div class=\"message bot-message\">\r\n");
      out.write("                                Hi! 👋 I'm your food delivery assistant. How can I help you today?\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-input-area\">\r\n");
      out.write("                            <input type=\"text\" id=\"chatInput\" placeholder=\"Type your message...\"\r\n");
      out.write("                                onkeypress=\"if(event.key === 'Enter') sendMessage()\">\r\n");
      out.write("                            <button onclick=\"sendMessage()\"><i class=\"fas fa-paper-plane\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    function toggleChat() {\r\n");
      out.write("                        const win = document.getElementById('chatWindow');\r\n");
      out.write("                        win.style.display = win.style.display === 'flex' ? 'none' : 'flex';\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    async function sendMessage() {\r\n");
      out.write("                        const input = document.getElementById('chatInput');\r\n");
      out.write("                        const msg = input.value.trim();\r\n");
      out.write("                        if (!msg) return;\r\n");
      out.write("\r\n");
      out.write("                        addMessage(msg, 'user');\r\n");
      out.write("                        input.value = '';\r\n");
      out.write("\r\n");
      out.write("                        try {\r\n");
      out.write("                            const response = await fetch('chat', {\r\n");
      out.write("                                method: 'POST',\r\n");
      out.write("                                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("                                body: 'message=' + encodeURIComponent(msg)\r\n");
      out.write("                            });\r\n");
      out.write("                            const botMsg = await response.text();\r\n");
      out.write("                            addMessage(botMsg, 'bot');\r\n");
      out.write("                        } catch (err) {\r\n");
      out.write("                            addMessage('Sorry, I am having trouble connecting right now.', 'bot');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function addMessage(text, sender) {\r\n");
      out.write("                        const container = document.getElementById('chatMessages');\r\n");
      out.write("                        const div = document.createElement('div');\r\n");
      out.write("                        div.className = 'message ' + (sender === 'user' ? 'user-message' : 'bot-message');\r\n");
      out.write("                        div.innerHTML = text.replace(/\\*\\*(.*?)\\*\\*/g, '<strong>$1</strong>'); // Simple bold support\r\n");
      out.write("                        container.appendChild(div);\r\n");
      out.write("                        container.scrollTop = container.scrollHeight;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // Search functionality\r\n");
      out.write("                    document.getElementById('searchInput').addEventListener('input', function (e) {\r\n");
      out.write("                        const searchTerm = e.target.value.toLowerCase();\r\n");
      out.write("                        const cards = document.querySelectorAll('.restaurant-card');\r\n");
      out.write("\r\n");
      out.write("                        cards.forEach(card => {\r\n");
      out.write("                            const name = card.querySelector('.restaurant-name').textContent.toLowerCase();\r\n");
      out.write("                            const cuisine = card.querySelector('.restaurant-cuisine').textContent.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("                            if (name.includes(searchTerm) || cuisine.includes(searchTerm)) {\r\n");
      out.write("                                card.style.display = 'block';\r\n");
      out.write("                            } else {\r\n");
      out.write("                                card.style.display = 'none';\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
