/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:25:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Login - FoodExpress</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("        <style>\r\n");
      out.write("            * {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                padding: 0;\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body {\r\n");
      out.write("                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                background: linear-gradient(135deg, #0F0F0F 0%, #1A1A1A 100%);\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Animated background elements */\r\n");
      out.write("            body::before {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                width: 500px;\r\n");
      out.write("                height: 500px;\r\n");
      out.write("                background: radial-gradient(circle, rgba(255, 107, 0, 0.1) 0%, transparent 70%);\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                top: -250px;\r\n");
      out.write("                right: -250px;\r\n");
      out.write("                animation: float 20s ease-in-out infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            body::after {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                height: 400px;\r\n");
      out.write("                background: radial-gradient(circle, rgba(255, 107, 0, 0.08) 0%, transparent 70%);\r\n");
      out.write("                border-radius: 50%;\r\n");
      out.write("                bottom: -200px;\r\n");
      out.write("                left: -200px;\r\n");
      out.write("                animation: float 15s ease-in-out infinite reverse;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes float {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: translate(0, 0) scale(1);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                50% {\r\n");
      out.write("                    transform: translate(50px, 50px) scale(1.1);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-container {\r\n");
      out.write("                background: rgba(26, 26, 26, 0.95);\r\n");
      out.write("                backdrop-filter: blur(10px);\r\n");
      out.write("                border-radius: 24px;\r\n");
      out.write("                padding: 50px 40px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                max-width: 450px;\r\n");
      out.write("                box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5),\r\n");
      out.write("                    0 0 0 1px rgba(255, 107, 0, 0.1);\r\n");
      out.write("                position: relative;\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("                animation: slideUp 0.6s ease-out;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes slideUp {\r\n");
      out.write("                from {\r\n");
      out.write("                    opacity: 0;\r\n");
      out.write("                    transform: translateY(30px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                to {\r\n");
      out.write("                    opacity: 1;\r\n");
      out.write("                    transform: translateY(0);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo-section {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-bottom: 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo-icon {\r\n");
      out.write("                width: 80px;\r\n");
      out.write("                height: 80px;\r\n");
      out.write("                background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                border-radius: 20px;\r\n");
      out.write("                display: inline-flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                box-shadow: 0 10px 30px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                animation: pulse 2s ease-in-out infinite;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes pulse {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: scale(1);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                50% {\r\n");
      out.write("                    transform: scale(1.05);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo-icon i {\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("                color: #FFFFFF;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo-section h1 {\r\n");
      out.write("                color: #FFFFFF;\r\n");
      out.write("                font-size: 32px;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                margin-bottom: 8px;\r\n");
      out.write("                letter-spacing: -0.5px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .logo-section p {\r\n");
      out.write("                color: #999;\r\n");
      out.write("                font-size: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group {\r\n");
      out.write("                margin-bottom: 25px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group label {\r\n");
      out.write("                display: block;\r\n");
      out.write("                color: #FFFFFF;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("                letter-spacing: 0.3px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-wrapper {\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-wrapper i {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 18px;\r\n");
      out.write("                top: 50%;\r\n");
      out.write("                transform: translateY(-50%);\r\n");
      out.write("                color: #666;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                transition: color 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 16px 18px 16px 50px;\r\n");
      out.write("                background: rgba(42, 42, 42, 0.8);\r\n");
      out.write("                border: 2px solid rgba(255, 107, 0, 0.2);\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                color: #FFFFFF;\r\n");
      out.write("                font-size: 15px;\r\n");
      out.write("                transition: all 0.3s;\r\n");
      out.write("                outline: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control:focus {\r\n");
      out.write("                border-color: #FF6B00;\r\n");
      out.write("                background: rgba(42, 42, 42, 1);\r\n");
      out.write("                box-shadow: 0 0 0 4px rgba(255, 107, 0, 0.1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control:focus+i {\r\n");
      out.write("                color: #FF6B00;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-control::placeholder {\r\n");
      out.write("                color: #666;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .remember-forgot {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .remember-me {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("                color: #999;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .remember-me input[type=\"checkbox\"] {\r\n");
      out.write("                width: 18px;\r\n");
      out.write("                height: 18px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                accent-color: #FF6B00;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .forgot-password {\r\n");
      out.write("                color: #FF6B00;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                transition: color 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .forgot-password:hover {\r\n");
      out.write("                color: #FFB84D;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 16px;\r\n");
      out.write("                background: linear-gradient(135deg, #FF6B00 0%, #FF8533 100%);\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                color: #FFFFFF;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all 0.3s;\r\n");
      out.write("                box-shadow: 0 8px 20px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                letter-spacing: 0.5px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:hover {\r\n");
      out.write("                transform: translateY(-2px);\r\n");
      out.write("                box-shadow: 0 12px 28px rgba(255, 107, 0, 0.4);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:active {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .divider {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin: 30px 0;\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .divider::before {\r\n");
      out.write("                content: '';\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                top: 50%;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 1px;\r\n");
      out.write("                background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .divider span {\r\n");
      out.write("                background: rgba(26, 26, 26, 0.95);\r\n");
      out.write("                padding: 0 15px;\r\n");
      out.write("                color: #666;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                z-index: 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-top: 25px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link p {\r\n");
      out.write("                color: #999;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link a {\r\n");
      out.write("                color: #FF6B00;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                transition: color 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .signup-link a:hover {\r\n");
      out.write("                color: #FFB84D;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .error-message {\r\n");
      out.write("                background: rgba(220, 53, 69, 0.1);\r\n");
      out.write("                border: 1px solid rgba(220, 53, 69, 0.3);\r\n");
      out.write("                color: #ff6b6b;\r\n");
      out.write("                padding: 12px 16px;\r\n");
      out.write("                border-radius: 10px;\r\n");
      out.write("                margin-bottom: 20px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("                animation: shake 0.5s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes shake {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: translateX(0);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                25% {\r\n");
      out.write("                    transform: translateX(-10px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                75% {\r\n");
      out.write("                    transform: translateX(10px);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .error-message i {\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            /* Responsive */\r\n");
      out.write("            @media (max-width: 480px) {\r\n");
      out.write("                .login-container {\r\n");
      out.write("                    padding: 40px 30px;\r\n");
      out.write("                    margin: 20px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .logo-section h1 {\r\n");
      out.write("                    font-size: 28px;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"login-container\">\r\n");
      out.write("            <div class=\"logo-section\">\r\n");
      out.write("                <div class=\"logo-icon\">\r\n");
      out.write("                    <i class=\"fas fa-utensils\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h1>FoodExpress</h1>\r\n");
      out.write("                <p>Welcome back! Please login to your account</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 String error=request.getParameter("error"); if (error !=null) { String
                message="An error occurred. Please try again." ; if (error.equals("notfound"))
                message="User not found. Please sign up." ; else if (error.equals("invalid"))
                message="Invalid password. Please try again." ; else if (error.equals("required"))
                message="All fields are required." ; 
      out.write("\r\n");
      out.write("                <div class=\"error-message\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle\"></i>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        ");
      out.print( message );
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 String success=request.getParameter("success"); if (success !=null && success.equals("signup")) {
                        
      out.write("\r\n");
      out.write("                        <div class=\"error-message\"\r\n");
      out.write("                            style=\"background: rgba(40, 167, 69, 0.1); border-color: rgba(40, 167, 69, 0.3); color: #28a745;\">\r\n");
      out.write("                            <i class=\"fas fa-check-circle\"></i>\r\n");
      out.write("                            <span>Registration successful! Please login.</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"LoginServlet\" method=\"POST\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"email\">Email Address</label>\r\n");
      out.write("                                    <div class=\"input-wrapper\">\r\n");
      out.write("                                        <input type=\"email\" id=\"email\" name=\"username\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Enter your email\" required autocomplete=\"email\">\r\n");
      out.write("                                        <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"password\">Password</label>\r\n");
      out.write("                                    <div class=\"input-wrapper\">\r\n");
      out.write("                                        <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Enter your password\" required autocomplete=\"current-password\">\r\n");
      out.write("                                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"remember-forgot\">\r\n");
      out.write("                                    <label class=\"remember-me\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"remember\">\r\n");
      out.write("                                        <span>Remember me</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <a href=\"#\" class=\"forgot-password\">Forgot Password?</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <button type=\"submit\" class=\"btn-login\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-in-alt\"></i> Sign In\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"divider\">\r\n");
      out.write("                                <span>OR</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"signup-link\">\r\n");
      out.write("                                <p>Don't have an account? <a href=\"signup.jsp\">Create Account</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
