/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:51:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import com.tap.model.Menu;
import com.tap.model.Cartitem;
import com.tap.model.Cart;
import com.tap.dapimplementation.MenuDaoImpl;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.model.Cartitem");
    _jspx_imports_classes.add("com.tap.model.Cart");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.tap.dapimplementation.MenuDaoImpl");
    _jspx_imports_classes.add("com.tap.model.Menu");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                            ");
 /* Authentication Check */ Object userObj=session.getAttribute("user"); if
                                (userObj==null) { response.sendRedirect("login.jsp"); return; } /* Cart for count only
                                */ Cart cart=(Cart) session.getAttribute("cart"); int cartCount=(cart !=null &&
                                cart.getItems() !=null) ? cart.getItems().size() : 0; /* Restaurant ID Handling */ int
                                restaurantId=1; String resIdParam=request.getParameter("restaurantId"); if (resIdParam
                                !=null && !resIdParam.isEmpty()) { try { restaurantId=Integer.parseInt(resIdParam);
                                session.setAttribute("restaurantId", Integer.valueOf(restaurantId)); } catch (Exception
                                nfe) { /* Keep default */ } } else { Object
                                sessionRestId=session.getAttribute("restaurantId"); if (sessionRestId !=null) {
                                restaurantId=((Integer) sessionRestId).intValue(); } } 
      out.write("\r\n");
      out.write("                                <!DOCTYPE html>\r\n");
      out.write("                                <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                                <head>\r\n");
      out.write("                                    <meta charset=\"UTF-8\">\r\n");
      out.write("                                    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                                    <title>Menu - FoodExpress</title>\r\n");
      out.write("                                    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("                                        rel=\"stylesheet\">\r\n");
      out.write("                                    <link rel=\"stylesheet\"\r\n");
      out.write("                                        href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" />\r\n");
      out.write("                                    <style>\r\n");
      out.write("                                        body {\r\n");
      out.write("                                            background: #f5f7fa;\r\n");
      out.write("                                            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .navbar-custom {\r\n");
      out.write("                                            background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                                            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .navbar-custom .navbar-brand {\r\n");
      out.write("                                            font-weight: bold;\r\n");
      out.write("                                            font-size: 24px;\r\n");
      out.write("                                            color: white !important;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .navbar-custom .nav-link {\r\n");
      out.write("                                            color: white !important;\r\n");
      out.write("                                            position: relative;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .cart-badge {\r\n");
      out.write("                                            position: absolute;\r\n");
      out.write("                                            top: 0;\r\n");
      out.write("                                            right: 0;\r\n");
      out.write("                                            transform: translate(50%, -50%);\r\n");
      out.write("                                            font-size: 10px;\r\n");
      out.write("                                            padding: 3px 6px;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .main-container {\r\n");
      out.write("                                            padding: 30px;\r\n");
      out.write("                                            max-width: 1200px;\r\n");
      out.write("                                            margin: 0 auto;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-section {\r\n");
      out.write("                                            display: grid;\r\n");
      out.write("                                            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));\r\n");
      out.write("                                            gap: 20px;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card {\r\n");
      out.write("                                            background: white;\r\n");
      out.write("                                            border-radius: 12px;\r\n");
      out.write("                                            overflow: hidden;\r\n");
      out.write("                                            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                                            transition: 0.3s;\r\n");
      out.write("                                            height: 100%;\r\n");
      out.write("                                            display: flex;\r\n");
      out.write("                                            flex-direction: column;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card:hover {\r\n");
      out.write("                                            transform: translateY(-5px);\r\n");
      out.write("                                            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card-image {\r\n");
      out.write("                                            width: 100%;\r\n");
      out.write("                                            height: 180px;\r\n");
      out.write("                                            object-fit: cover;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card-content {\r\n");
      out.write("                                            padding: 20px;\r\n");
      out.write("                                            flex-grow: 1;\r\n");
      out.write("                                            display: flex;\r\n");
      out.write("                                            flex-direction: column;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card-title {\r\n");
      out.write("                                            font-weight: 700;\r\n");
      out.write("                                            font-size: 18px;\r\n");
      out.write("                                            margin-bottom: 8px;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card-description {\r\n");
      out.write("                                            font-size: 13px;\r\n");
      out.write("                                            color: #666;\r\n");
      out.write("                                            margin-bottom: 15px;\r\n");
      out.write("                                            flex-grow: 1;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-card-footer {\r\n");
      out.write("                                            display: flex;\r\n");
      out.write("                                            justify-content: space-between;\r\n");
      out.write("                                            align-items: center;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .menu-price {\r\n");
      out.write("                                            font-weight: 800;\r\n");
      out.write("                                            font-size: 20px;\r\n");
      out.write("                                            color: #FF6B00;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .btn-add {\r\n");
      out.write("                                            background: #FF6B00;\r\n");
      out.write("                                            color: white;\r\n");
      out.write("                                            border: none;\r\n");
      out.write("                                            padding: 10px 15px;\r\n");
      out.write("                                            border-radius: 8px;\r\n");
      out.write("                                            font-weight: 600;\r\n");
      out.write("                                            cursor: pointer;\r\n");
      out.write("                                            transition: 0.3s;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .btn-add:hover {\r\n");
      out.write("                                            background: #E65A00;\r\n");
      out.write("                                        }\r\n");
      out.write("\r\n");
      out.write("                                        .toast-container {\r\n");
      out.write("                                            position: fixed;\r\n");
      out.write("                                            bottom: 20px;\r\n");
      out.write("                                            right: 20px;\r\n");
      out.write("                                            z-index: 1050;\r\n");
      out.write("                                        }\r\n");
      out.write("                                    </style>\r\n");
      out.write("                                </head>\r\n");
      out.write("\r\n");
      out.write("                                <body>\r\n");
      out.write("                                    <nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom sticky-top\">\r\n");
      out.write("                                        <div class=\"container\">\r\n");
      out.write("                                            <a class=\"navbar-brand\" href=\"home.jsp\"><i\r\n");
      out.write("                                                    class=\"fas fa-utensils me-2\"></i>FoodExpress</a>\r\n");
      out.write("                                            <div class=\"ms-auto d-flex align-items-center\">\r\n");
      out.write("                                                <a href=\"home.jsp\" class=\"nav-link me-3\"><i\r\n");
      out.write("                                                        class=\"fas fa-home me-1\"></i>Home</a>\r\n");
      out.write("                                                <a href=\"orders\" class=\"nav-link me-3\"><i\r\n");
      out.write("                                                        class=\"fas fa-shopping-bag me-1\"></i>My Orders</a>\r\n");
      out.write("                                                <a href=\"cart.jsp\" class=\"nav-link me-3\">\r\n");
      out.write("                                                    <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                                                    ");
 if (cartCount> 0) { 
      out.write("\r\n");
      out.write("                                                        <span class=\"badge bg-danger rounded-pill cart-badge\">\r\n");
      out.write("                                                            ");
      out.print( cartCount );
      out.write("\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        ");
 } 
      out.write("\r\n");
      out.write("                                                            Cart\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <a href=\"LogoutServlet\" class=\"nav-link\"><i\r\n");
      out.write("                                                        class=\"fas fa-sign-out-alt me-1\"></i>Logout</a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </nav>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"main-container\">\r\n");
      out.write("                                        <div class=\"mb-4 d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h2 class=\"fw-bold\">Menu</h2>\r\n");
      out.write("                                                <p class=\"text-muted\">Discover delicious dishes from this restaurant</p>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <a href=\"cart.jsp\" class=\"btn btn-outline-primary rounded-pill px-4\">\r\n");
      out.write("                                                <i class=\"fas fa-shopping-basket me-2\"></i>View Cart\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"menu-section\">\r\n");
      out.write("                                            ");
 try { MenuDaoImpl menuDao=new MenuDaoImpl(); List<Menu> menuItems =
                                                menuDao.getMenuByRestaurant(restaurantId);
                                                if (menuItems != null && !menuItems.isEmpty()) {
                                                for (Menu menu : menuItems) {
                                                String img = menu.getImageUrl();
                                                if (img == null || img.isEmpty()) { img = "images/menu/default.jpg"; }
                                                
      out.write("\r\n");
      out.write("                                                <div class=\"menu-card\">\r\n");
      out.write("                                                    <img src=\"");
      out.print( img );
      out.write("\" class=\"menu-card-image\"\r\n");
      out.write("                                                        alt=\"");
      out.print( menu.getItemName() );
      out.write("\">\r\n");
      out.write("                                                    <div class=\"menu-card-content\">\r\n");
      out.write("                                                        <div class=\"menu-card-title\">\r\n");
      out.write("                                                            ");
      out.print( menu.getItemName() );
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"menu-card-description\">\r\n");
      out.write("                                                            ");
      out.print( menu.getDescription() );
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"menu-card-footer\">\r\n");
      out.write("                                                            <div class=\"menu-price\">&#8377; ");
      out.print( menu.getPrice() );
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <form method=\"POST\" action=\"CartServlet\"\r\n");
      out.write("                                                                class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("                                                                <input type=\"hidden\" name=\"menuId\"\r\n");
      out.write("                                                                    value=\"");
      out.print( menu.getMenuId() );
      out.write("\">\r\n");
      out.write("                                                                <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                                                                <input type=\"hidden\" name=\"from\" value=\"menu\">\r\n");
      out.write("                                                                <input type=\"number\" name=\"quantity\" value=\"1\" min=\"1\"\r\n");
      out.write("                                                                    max=\"10\" class=\"form-control form-control-sm\"\r\n");
      out.write("                                                                    style=\"width: 50px;\">\r\n");
      out.write("                                                                <button type=\"submit\" class=\"btn-add\"><i\r\n");
      out.write("                                                                        class=\"fas fa-plus\"></i></button>\r\n");
      out.write("                                                            </form>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                ");
 } } else { 
      out.write("\r\n");
      out.write("                                                    <div class=\"text-center py-5 w-100\" style=\"grid-column: 1/-1;\">\r\n");
      out.write("                                                        <i class=\"fas fa-utensils fa-3x text-muted mb-3\"></i>\r\n");
      out.write("                                                        <h4>No items available for this restaurant.</h4>\r\n");
      out.write("                                                        <a href=\"home.jsp\"\r\n");
      out.write("                                                            class=\"btn btn-primary mt-3 px-4 rounded-pill\">Back to\r\n");
      out.write("                                                            Restaurants</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    ");
 } } catch (Exception ex) { 
      out.write("\r\n");
      out.write("                                                        <div class=\"alert alert-danger w-100\"\r\n");
      out.write("                                                            style=\"grid-column: 1/-1;\">\r\n");
      out.write("                                                            Error loading menu. Please try again later.\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        ");
 } 
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    ");
 if (request.getParameter("added") !=null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"toast-container\">\r\n");
      out.write("                                            <div class=\"toast show align-items-center text-white bg-success border-0\"\r\n");
      out.write("                                                role=\"alert\">\r\n");
      out.write("                                                <div class=\"d-flex\">\r\n");
      out.write("                                                    <div class=\"toast-body\">\r\n");
      out.write("                                                        Item added to cart successfully!\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <button type=\"button\" class=\"btn-close btn-close-white me-2 m-auto\"\r\n");
      out.write("                                                        data-bs-dismiss=\"toast\"></button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <script>\r\n");
      out.write("                                            setTimeout(() => {\r\n");
      out.write("                                                document.querySelector('.toast').classList.remove('show');\r\n");
      out.write("                                            }, 3000);\r\n");
      out.write("                                        </script>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                </body>\r\n");
      out.write("\r\n");
      out.write("                                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
