/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.tap.model.Cart;
import com.tap.model.Cartitem;
import com.tap.model.User;
import java.util.Map;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.tap.model.Cart");
    _jspx_imports_classes.add("com.tap.model.Cartitem");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.tap.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");
 Cart cart=(Cart) session.getAttribute("cart"); User user=(User) session.getAttribute("user"); if (cart==null
            || cart.getItems().isEmpty()) { response.sendRedirect("menu-cart.jsp"); return; } String displayAddress="" ;
            if (user !=null && user.getAddress() !=null) { displayAddress=user.getAddress(); } double subtotal=0; for
            (Cartitem item : cart.getItems().values()) { subtotal +=item.getPrice() * item.getQuantity(); } double
            deliveryFee=50.00; double tax=subtotal * 0.05; double totalAmount=subtotal + deliveryFee + tax; 
      out.write("\r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>Payment - FoodExpress</title>\r\n");
      out.write("                <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("                <link rel=\"stylesheet\"\r\n");
      out.write("                    href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" />\r\n");
      out.write("                <style>\r\n");
      out.write("                    body {\r\n");
      out.write("                        background: #f5f7fa;\r\n");
      out.write("                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .navbar-custom {\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .navbar-custom .navbar-brand {\r\n");
      out.write("                        font-weight: bold;\r\n");
      out.write("                        font-size: 24px;\r\n");
      out.write("                        color: white !important;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .checkout-container {\r\n");
      out.write("                        max-width: 1000px;\r\n");
      out.write("                        margin: 40px auto;\r\n");
      out.write("                        padding: 0 20px;\r\n");
      out.write("                        display: grid;\r\n");
      out.write("                        grid-template-columns: 1fr 350px;\r\n");
      out.write("                        gap: 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    @media (max-width: 768px) {\r\n");
      out.write("                        .checkout-container {\r\n");
      out.write("                            grid-template-columns: 1fr;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .card {\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        border-radius: 15px;\r\n");
      out.write("                        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("                        margin-bottom: 20px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .card-header {\r\n");
      out.write("                        background: white;\r\n");
      out.write("                        border-bottom: 1px solid #eee;\r\n");
      out.write("                        padding: 20px;\r\n");
      out.write("                        border-radius: 15px 15px 0 0 !important;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        font-size: 18px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .card-body {\r\n");
      out.write("                        padding: 25px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option {\r\n");
      out.write("                        border: 2px solid #f0f0f0;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        padding: 15px;\r\n");
      out.write("                        margin-bottom: 15px;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: 0.3s;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 15px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option:hover {\r\n");
      out.write("                        border-color: #FF6B00;\r\n");
      out.write("                        background: #fffcf5;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option.active {\r\n");
      out.write("                        border-color: #FF6B00;\r\n");
      out.write("                        background: #fffcf5;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option input {\r\n");
      out.write("                        display: none;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option i {\r\n");
      out.write("                        font-size: 24px;\r\n");
      out.write("                        width: 30px;\r\n");
      out.write("                        text-align: center;\r\n");
      out.write("                        color: #666;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .payment-option.active i {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .order-summary-row {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        margin-bottom: 10px;\r\n");
      out.write("                        color: #666;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .order-total-row {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        margin-top: 15px;\r\n");
      out.write("                        padding-top: 15px;\r\n");
      out.write("                        border-top: 2px dashed #eee;\r\n");
      out.write("                        font-weight: 800;\r\n");
      out.write("                        font-size: 20px;\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-pay {\r\n");
      out.write("                        width: 100%;\r\n");
      out.write("                        padding: 15px;\r\n");
      out.write("                        background: #FF6B00;\r\n");
      out.write("                        color: white;\r\n");
      out.write("                        border: none;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        font-size: 18px;\r\n");
      out.write("                        margin-top: 20px;\r\n");
      out.write("                        transition: 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-pay:hover {\r\n");
      out.write("                        background: #E65A00;\r\n");
      out.write("                        transform: translateY(-2px);\r\n");
      out.write("                        box-shadow: 0 5px 15px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .form-label {\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        color: #444;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .form-control {\r\n");
      out.write("                        border-radius: 10px;\r\n");
      out.write("                        padding: 12px;\r\n");
      out.write("                        border: 1px solid #ddd;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .form-control:focus {\r\n");
      out.write("                        border-color: #FF6B00;\r\n");
      out.write("                        box-shadow: 0 0 0 0.2rem rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom sticky-top\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"home.jsp\"><i class=\"fas fa-utensils me-2\"></i>FoodExpress</a>\r\n");
      out.write("                        <div class=\"ms-auto\">\r\n");
      out.write("                            <a href=\"home.jsp\" class=\"nav-link d-inline-block me-3 text-white text-decoration-none\"><i\r\n");
      out.write("                                    class=\"fas fa-home me-1\"></i>Home</a>\r\n");
      out.write("                            <a href=\"orders\" class=\"nav-link d-inline-block text-white text-decoration-none\"><i\r\n");
      out.write("                                    class=\"fas fa-shopping-bag me-1\"></i>My Orders</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"checkout-container\">\r\n");
      out.write("                    <!-- Main Form -->\r\n");
      out.write("                    <div class=\"checkout-main\">\r\n");
      out.write("                        <form action=\"PaymentServlet\" method=\"POST\" id=\"paymentForm\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt me-2 text-primary\"></i>Delivery Address\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\">Complete Address</label>\r\n");
      out.write("                                        <textarea name=\"address\" class=\"form-control\" rows=\"3\"\r\n");
      out.write("                                            placeholder=\"Enter your full delivery address...\"\r\n");
      out.write("                                            required>");
      out.print( displayAddress );
      out.write("</textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <i class=\"fas fa-credit-card me-2 text-primary\"></i>Payment Method\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <label class=\"payment-option active\">\r\n");
      out.write("                                        <input type=\"radio\" name=\"paymentMethod\" value=\"COD\" checked>\r\n");
      out.write("                                        <i class=\"fas fa-money-bill-wave\"></i>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <div class=\"fw-bold\">Cash on Delivery</div>\r\n");
      out.write("                                            <div class=\"small text-muted\">Pay when your food arrives</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </label>\r\n");
      out.write("\r\n");
      out.write("                                    <label class=\"payment-option\">\r\n");
      out.write("                                        <input type=\"radio\" name=\"paymentMethod\" value=\"CARD\">\r\n");
      out.write("                                        <i class=\"fas fa-credit-card\"></i>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <div class=\"fw-bold\">Credit / Debit Card</div>\r\n");
      out.write("                                            <div class=\"small text-muted\">Secure online payment</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </label>\r\n");
      out.write("\r\n");
      out.write("                                    <label class=\"payment-option\">\r\n");
      out.write("                                        <input type=\"radio\" name=\"paymentMethod\" value=\"UPI\">\r\n");
      out.write("                                        <i class=\"fas fa-mobile-alt\"></i>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <div class=\"fw-bold\">UPI</div>\r\n");
      out.write("                                            <div class=\"small text-muted\">Instant mobile payment</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sidebar Summary -->\r\n");
      out.write("                <div class=\"checkout-sidebar\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-header\">Order Summary</div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"order-summary-row\">\r\n");
      out.write("                                <span>Items Total</span>\r\n");
      out.write("                                <span>&#8377; ");
      out.print( String.format("%.2f", subtotal) );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"order-summary-row\">\r\n");
      out.write("                                <span>Delivery Fee</span>\r\n");
      out.write("                                <span>&#8377; ");
      out.print( String.format("%.2f", deliveryFee) );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"order-summary-row\">\r\n");
      out.write("                                <span>Taxes (5%)</span>\r\n");
      out.write("                                <span>&#8377; ");
      out.print( String.format("%.2f", tax) );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"order-total-row\">\r\n");
      out.write("                                <span>Total</span>\r\n");
      out.write("                                <span>&#8377; ");
      out.print( String.format("%.2f", totalAmount) );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" form=\"paymentForm\" class=\"btn-pay\">Place Order</button>\r\n");
      out.write("                            <a href=\"menu-cart.jsp\" class=\"btn btn-light w-100 mt-3 border rounded-pill\">Back to\r\n");
      out.write("                                Cart</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    document.querySelectorAll('.payment-option').forEach(option => {\r\n");
      out.write("                        option.addEventListener('click', function () {\r\n");
      out.write("                            document.querySelectorAll('.payment-option').forEach(opt => opt.classList.remove('active'));\r\n");
      out.write("                            this.classList.add('active');\r\n");
      out.write("                            this.querySelector('input').checked = true;\r\n");
      out.write("                        });\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
