/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2026-02-03 17:52:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.tap.model.User;
import java.util.List;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");
 User user=(User) session.getAttribute("user"); if (user==null) { response.sendRedirect("login.jsp"); return;
            } 
      out.write("\r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>My Profile - FoodExpress</title>\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("                <style>\r\n");
      out.write("                    * {\r\n");
      out.write("                        margin: 0;\r\n");
      out.write("                        padding: 0;\r\n");
      out.write("                        box-sizing: border-box;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    body {\r\n");
      out.write("                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("                        background: #0F0F0F;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        min-height: 100vh;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Navbar */\r\n");
      out.write("                    .navbar {\r\n");
      out.write("                        background: rgba(26, 26, 26, 0.95);\r\n");
      out.write("                        backdrop-filter: blur(10px);\r\n");
      out.write("                        padding: 20px 0;\r\n");
      out.write("                        position: sticky;\r\n");
      out.write("                        top: 0;\r\n");
      out.write("                        z-index: 1000;\r\n");
      out.write("                        border-bottom: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .navbar-container {\r\n");
      out.write("                        max-width: 1400px;\r\n");
      out.write("                        margin: 0 auto;\r\n");
      out.write("                        padding: 0 30px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        justify-content: space-between;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 12px;\r\n");
      out.write("                        text-decoration: none;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-icon {\r\n");
      out.write("                        width: 45px;\r\n");
      out.write("                        height: 45px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-icon i {\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        font-size: 22px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .logo-text {\r\n");
      out.write("                        font-size: 26px;\r\n");
      out.write("                        font-weight: 700;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-links {\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        gap: 20px;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-link {\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                        text-decoration: none;\r\n");
      out.write("                        padding: 8px 16px;\r\n");
      out.write("                        border-radius: 8px;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .nav-link:hover {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                        background: rgba(255, 107, 0, 0.1);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    /* Profile Layout */\r\n");
      out.write("                    .profile-container {\r\n");
      out.write("                        max-width: 1000px;\r\n");
      out.write("                        margin: 60px auto;\r\n");
      out.write("                        padding: 0 30px;\r\n");
      out.write("                        animation: fadeIn 0.8s ease;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    @keyframes fadeIn {\r\n");
      out.write("                        from {\r\n");
      out.write("                            opacity: 0;\r\n");
      out.write("                            transform: translateY(20px);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        to {\r\n");
      out.write("                            opacity: 1;\r\n");
      out.write("                            transform: translateY(0);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .profile-header {\r\n");
      out.write("                        background: linear-gradient(135deg, #1A1A1A 0%, #0F0F0F 100%);\r\n");
      out.write("                        border-radius: 24px;\r\n");
      out.write("                        padding: 40px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 30px;\r\n");
      out.write("                        border: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                        margin-bottom: 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .profile-avatar {\r\n");
      out.write("                        width: 120px;\r\n");
      out.write("                        height: 120px;\r\n");
      out.write("                        background: linear-gradient(135deg, #FF6B00 0%, #FFB84D 100%);\r\n");
      out.write("                        border-radius: 50%;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        justify-content: center;\r\n");
      out.write("                        font-size: 48px;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        box-shadow: 0 10px 30px rgba(255, 107, 0, 0.3);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .profile-info h1 {\r\n");
      out.write("                        font-size: 32px;\r\n");
      out.write("                        margin-bottom: 8px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .profile-info p {\r\n");
      out.write("                        color: #999;\r\n");
      out.write("                        font-size: 16px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .profile-grid {\r\n");
      out.write("                        display: grid;\r\n");
      out.write("                        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("                        gap: 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-card {\r\n");
      out.write("                        background: rgba(26, 26, 26, 0.8);\r\n");
      out.write("                        border-radius: 20px;\r\n");
      out.write("                        padding: 30px;\r\n");
      out.write("                        border: 1px solid rgba(255, 107, 0, 0.1);\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-card:hover {\r\n");
      out.write("                        border-color: rgba(255, 107, 0, 0.3);\r\n");
      out.write("                        transform: translateY(-5px);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-card h3 {\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                        font-size: 18px;\r\n");
      out.write("                        margin-bottom: 20px;\r\n");
      out.write("                        display: flex;\r\n");
      out.write("                        align-items: center;\r\n");
      out.write("                        gap: 10px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-item {\r\n");
      out.write("                        margin-bottom: 15px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-label {\r\n");
      out.write("                        color: #666;\r\n");
      out.write("                        font-size: 14px;\r\n");
      out.write("                        margin-bottom: 5px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .info-value {\r\n");
      out.write("                        font-size: 16px;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                        font-weight: 500;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-edit {\r\n");
      out.write("                        background: rgba(255, 107, 0, 0.1);\r\n");
      out.write("                        border: 1px solid #FF6B00;\r\n");
      out.write("                        color: #FF6B00;\r\n");
      out.write("                        padding: 12px 24px;\r\n");
      out.write("                        border-radius: 12px;\r\n");
      out.write("                        font-weight: 600;\r\n");
      out.write("                        cursor: pointer;\r\n");
      out.write("                        transition: all 0.3s;\r\n");
      out.write("                        margin-top: 20px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .btn-edit:hover {\r\n");
      out.write("                        background: #FF6B00;\r\n");
      out.write("                        color: #FFFFFF;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    @media (max-width: 768px) {\r\n");
      out.write("                        .profile-header {\r\n");
      out.write("                            flex-direction: column;\r\n");
      out.write("                            text-align: center;\r\n");
      out.write("                            padding: 30px;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </style>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("                <!-- Navbar -->\r\n");
      out.write("                <nav class=\"navbar\">\r\n");
      out.write("                    <div class=\"navbar-container\">\r\n");
      out.write("                        <a href=\"home\" class=\"logo\">\r\n");
      out.write("                            <div class=\"logo-icon\">\r\n");
      out.write("                                <i class=\"fas fa-utensils\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <span class=\"logo-text\">FoodExpress</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"nav-links\">\r\n");
      out.write("                            <a href=\"home\" class=\"nav-link\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("                            <a href=\"menu-cart.jsp\" class=\"nav-link\"><i class=\"fas fa-shopping-cart\"></i> Cart</a>\r\n");
      out.write("                            <a href=\"LogoutServlet\" class=\"nav-link\"><i class=\"fas fa-sign-out-alt\"></i> Logout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"profile-container\">\r\n");
      out.write("                    <div class=\"profile-header\">\r\n");
      out.write("                        <div class=\"profile-avatar\">\r\n");
      out.write("                            ");
      out.print( user.getName().substring(0, 1).toUpperCase() );
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profile-info\">\r\n");
      out.write("                            <h1>Welcome, ");
      out.print( user.getName() );
      out.write("!</h1>\r\n");
      out.write("                            <p>Member since October 2023</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"profile-grid\">\r\n");
      out.write("                        <div class=\"info-card\">\r\n");
      out.write("                            <h3><i class=\"fas fa-user-circle\"></i> Personal Details</h3>\r\n");
      out.write("                            <div class=\"info-item\">\r\n");
      out.write("                                <div class=\"info-label\">Full Name</div>\r\n");
      out.write("                                <div class=\"info-value\">\r\n");
      out.write("                                    ");
      out.print( user.getName() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"info-item\">\r\n");
      out.write("                                <div class=\"info-label\">Email Address</div>\r\n");
      out.write("                                <div class=\"info-value\">\r\n");
      out.write("                                    ");
      out.print( user.getEmail() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"info-item\">\r\n");
      out.write("                                <div class=\"info-label\">Phone Number</div>\r\n");
      out.write("                                <div class=\"info-value\">\r\n");
      out.write("                                    ");
      out.print( user.getPhone() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"info-card\">\r\n");
      out.write("                            <h3><i class=\"fas fa-map-marker-alt\"></i> Delivery Address</h3>\r\n");
      out.write("                            <div class=\"info-item\">\r\n");
      out.write("                                <div class=\"info-label\">Current Address</div>\r\n");
      out.write("                                <div class=\"info-value\">\r\n");
      out.write("                                    ");
      out.print( user.getAddress() );
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"btn-edit\">Update Address</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- My Orders Section -->\r\n");
      out.write("                    <div style=\"margin-top: 50px;\">\r\n");
      out.write("                        <h2 style=\"margin-bottom: 30px; font-size: 28px;\">My Recent Orders</h2>\r\n");
      out.write("                        ");
 List<com.tap.model.Order> orders = (List<com.tap.model.Order>)
                                request.getAttribute("orders");
                                if (orders == null || orders.isEmpty()) {
                                
      out.write("\r\n");
      out.write("                                <div class=\"info-card\" style=\"text-align: center; padding: 50px;\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-bag\"\r\n");
      out.write("                                        style=\"font-size: 48px; color: #333; margin-bottom: 20px;\"></i>\r\n");
      out.write("                                    <p style=\"color: #666;\">You haven't placed any orders yet.</p>\r\n");
      out.write("                                    <a href=\"home\" class=\"btn-edit\"\r\n");
      out.write("                                        style=\"display: inline-block; text-decoration: none; margin-top: 20px;\">Order\r\n");
      out.write("                                        Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    <div style=\"display: flex; flex-direction: column; gap: 20px;\">\r\n");
      out.write("                                        ");
 for (com.tap.model.Order order : orders) { 
      out.write("\r\n");
      out.write("                                            <div class=\"info-card\"\r\n");
      out.write("                                                style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("                                                <div>\r\n");
      out.write("                                                    <div\r\n");
      out.write("                                                        style=\"font-size: 14px; color: #FF6B00; font-weight: 600; margin-bottom: 5px;\">\r\n");
      out.write("                                                        ORDER #");
      out.print( order.getOrderId() );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div style=\"font-size: 18px; font-weight: 700; margin-bottom: 5px;\">\r\n");
      out.write("                                                        ");
      out.print( order.getOrderDate() );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div style=\"color: #999; font-size: 14px;\">\r\n");
      out.write("                                                        Payment: ");
      out.print( order.getPaymentMode() );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div style=\"text-align: right;\">\r\n");
      out.write("                                                    <div\r\n");
      out.write("                                                        style=\"font-size: 20px; font-weight: 800; color: #FFFFFF; margin-bottom: 8px;\">\r\n");
      out.write("                                                        &#8377;");
      out.print( String.format("%.2f", order.getTotalAmount()) );
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <span\r\n");
      out.write("                                                        style=\"background: rgba(46, 204, 113, 0.1); color: #2ecc71; padding: 6px 15px; border-radius: 50px; font-size: 12px; font-weight: 600; text-transform: uppercase;\">\r\n");
      out.write("                                                        ");
      out.print( order.getStatus() );
      out.write("\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
